---
- name: WSL インスタンスセットアップ
  hosts: localhost
  become: yes
  roles:
    - wsl_tools
    - wsl_user
    - wsl_config

- name: 開発環境セットアップ
  hosts: localhost
  become: yes
  become_user: "{{ wsl_user_name }}"
  roles:
    - prepare_git
    - prepare_common
    - prepare_docker
    - prepare_container_db
    - prepare_container_redmine
