---
- name: 開発用グループ作成
  become: yes
  ansible.builtin.group:
    name: "{{ wsl_group_name }}"
    gid: "{{ wsl_gid }}"

- name: 開発用ユーザー作成
  ansible.builtin.user:
    name: "{{ wsl_user_name }}"
    uid: "{{ wsl_uid }}"
    password: "{{ wsl_user_password | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes
    group: "{{ wsl_gid }}"
    groups: sudo
    append: yes

- name: sudoers設定
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ wsl_user_name }}"
    content: "{{ wsl_user_name }} ALL=(ALL) ALL"
    mode: "0440"
