---
- name: WSL インスタンスセットアップ
  hosts: localhost
  become: yes
  roles:
    - common
    - user
    - wsl

- name: 開発環境セットアップ
  hosts: localhost
  become: yes
  become_user: "{{ wsl_user_name }}"
  roles:
    - prepare
    - git
    - docker
    - db
