---
- name: Redmine コンテナ用 secrets ディレクトリ作成
  ansible.builtin.file:
    path: "{{ redmine_secrets_dir }}"
    state: directory
    owner: "{{ wsl_uid }}"
    group: "{{ wsl_gid }}"
    mode: '0700' # wsl_uid を指定してコンテナを起動するため 0700 に設定

- name: Redmine API キーファイル生成 (ファイルが存在しない場合のみ)
  ansible.builtin.shell:
    cmd: "openssl rand -hex 20 > {{ redmine_api_key_file }}"
    creates: "{{ redmine_api_key_file }}"

- name: Redmine API キーファイル権限設定
  ansible.builtin.file:
    path: "{{ redmine_api_key_file }}"
    owner: "{{ wsl_uid }}"
    group: "{{ wsl_gid }}"
    mode: '0600' # wsl_uid を指定してコンテナを起動するため 0600 に設定
